[versions]
agp = "8.9.2"
kotlin = "2.1.0"
coreKtx = "1.13.1"
activityCompose = "1.10.1"
material3 = "1.3.2"
rules = "1.5.0"
runner = "1.5.2"
orchSDK = "0.1.0"
kotlinCoroutines = "1.8.1"
screenshot = "0.0.1-alpha08"
seonGradle = "0.33.5"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "rules" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
seon-orchestration = { group = "io.seon", name = "orchestration-android-sdk", version.ref = "orchSDK" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
